INSERT INTO TB_USER(USER_SEQ, ID,PASSWORD, NAME, REFRESH_TOKEN) VALUES (null, 'user1','{bcrypt}$2a$10$yeY6ccu1KT6kLK1gMIRjROTvczP/mJN6bXEIlt7NNPN4lxO7TiN0.', 'user', null);
INSERT INTO TB_USER(USER_SEQ, ID,PASSWORD, NAME, REFRESH_TOKEN) VALUES (null, 'user2','{bcrypt}$2a$10$yeY6ccu1KT6kLK1gMIRjROTvczP/mJN6bXEIlt7NNPN4lxO7TiN0.', 'user', null);
INSERT INTO TB_USER(USER_SEQ, ID,PASSWORD, NAME, REFRESH_TOKEN) VALUES (null, 'user3','{bcrypt}$2a$10$yeY6ccu1KT6kLK1gMIRjROTvczP/mJN6bXEIlt7NNPN4lxO7TiN0.', 'user', null);
INSERT INTO TB_USER(USER_SEQ, ID,PASSWORD, NAME, REFRESH_TOKEN) VALUES (null, 'user4','{bcrypt}$2a$10$yeY6ccu1KT6kLK1gMIRjROTvczP/mJN6bXEIlt7NNPN4lxO7TiN0.', 'user', null);

INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk001', '국민은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk002', '기타은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk003', '농협은행/수협은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk004', '신한은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk005', '외환은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk006', '우리은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk007', '주택도시기금');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk008', '하나은행');
INSERT INTO TB_BANK(INSTITUTE_CODE, INSTITUTE_NAME) VALUES('bnk009', '한국시티은행');